 # Define school specific parameters
school:
  name: MY LOCAL CONFIG
  abbrev: MLC
  ipeds: 198668
  fice: "008083"
  usgov: 37087
  ncccs: 842
  instid: 0019844
  inststate: NC
  instcountry: US
  branch: "00"

# Define database specific parameters
sql:
  # Name of the database server
  server: researchvm.haywood.edu
  # Name of the database on the above server
  db: CCDW_HIST
  # Driver for ODBC connections
  driver: ODBC Driver 17 for SQL Server

  ###
  ### You should not have to change the following items in this section
  ###

  # Schema in above database where loaded data will be uploaded
  schema_input: input

  # Schema in above database where loaded data will be moved to history
  schema_history: history

  # Schema in above database where local tables, including configuration, will be uploaded
  schema_local: local

  # Schema in above database where final data wharehouse data will be uploaded
  schema_ccdw: ccdw

  # Schema in above database where audit data will be uploaded
  schema_audit: dw_dim

  # Template file names for create, merge, and alter table statements
  merge_scd1: //helix/divisions/IERG/ccdw/templates/sql/SQL_MERGE_TEMPLATE_SCD1.sql
  merge_scd2: //helix/divisions/IERG/ccdw/templates/sql/SQL_MERGE_TEMPLATE_SCD2.sql
  add_Columns: //helix/divisions/IERG/ccdw/templates/sql/SQL_ALTER_TEMPLATE.sql
  drop_view: //helix/divisions/IERG/ccdw/templates/sql/SQL_DROP_VIEW_TEMPLATE.sql 
  delete_table_data: //helix/divisions/IERG/ccdw/templates/sql/SQL_DELETE_TABLE_DATA_TEMPLATE.sql
  view_create: //helix/divisions/IERG/ccdw/templates/sql/SQL_VIEW_TEMPLATE.sql
  view2_create: //helix/divisions/IERG/ccdw/templates/sql/SQL_VIEW2_TEMPLATE.sql
  view2_cast: //helix/divisions/IERG/ccdw/templates/sql/SQL_VIEW2_CAST_TEMPLATE.sql
  view2_crossapply: //helix/divisions/IERG/ccdw/templates/sql/SQL_VIEW2_CROSSAPPLY_TEMPLATE.sql
  view2_whereand: //helix/divisions/IERG/ccdw/templates/sql/SQL_VIEW2_WHEREAND_TEMPLATE.sql
  view3_create: //helix/divisions/IERG/ccdw/templates/sql/SQL_VIEW3_TEMPLATE.sql
  table_names: //helix/divisions/IERG/ccdw/templates/sql/SQL_TABLE_NAMES_TEMPLATE.sql
  table_column_names: //helix/divisions/IERG/ccdw/templates/sql/SQL_TABLE_COLUMN_NAMES_TEMPLATE.sql
  alter_table_keys: //helix/divisions/IERG/ccdw/templates/sql/SQL_ALTER_TABLE_KEYS_TEMPLATE.sql
  alter_table_key_column: //helix/divisions/IERG/ccdw/templates/sql/SQL_ALTER_TABLE_KEY_COLUMN_TEMPLATE.sql
  alter_table_add: //helix/divisions/IERG/ccdw/templates/sql/SQL_ALTER_ADD_TEMPLATE.sql
  alter_table_column: //helix/divisions/IERG/ccdw/templates/sql/SQL_ALTER_TABLE_COLUMN_TEMPLATE.sql
  audit_create_record: //helix/divisions/IERG/ccdw/templates/sql/SQL_INSERT_AUDIT_TEMPLATE.sql
  audit_update_record: //helix/divisions/IERG/ccdw/templates/sql/SQL_UPDATE_AUDIT_TEMPLATE.sql

# Define informer specific parameters
informer:
  export_path: //informer/donder/DW/
  export_path_wStatus: //informer/donder/DW___wStatus/
  export_path_meta: //informer/donder/META/
  
  stage_path: ./data_stage/

  ###
  ### You should not have to change the following items
  ###
  
  # Prefix for all informer reports
  prefix: DW_
  # The latest version of reports that appear in the above location
  latest_version: 1005

ccdw:
  ccdw_path: //helix/divisions/IERG/ccdw/
  log_path: //helix/divisions/IERG/ccdw/log/

  # Paths for output and archive files
  archive_path: //helix/divisions/IERG/ccdw/archive/import/
  archive_path_wStatus: //helix/divisions/IERG/ccdw/archive/wStatus/
  invalid_path_wStatus: //helix/divisions/IERG/ccdw/archive/wStatus_INVALID/
  archive_type: move # Can be move or zip

  error_path: //helix/divisions/IERG/ccdw/error/
  error_output: true

  ###
  ### You should not have to change the following items in this section
  ###

  log_level: info
  meta_custom: //helix/divisions/IERG/ccdw/META__CUSTOM_CDD.csv
  new_fields_fn: //helix/divisions/IERG/ccdw/NEW_FIELDS.csv

status_fields: 
  ACAD_PROGRAMS        : ['ACPG.STATUS', 'ACPG.STATUS.DATE']
  APPLICATIONS         : ['APPL.STATUS', 'APPL.STATUS.DATE', 'APPL.STATUS.TIME']
  COURSES              : ['CRS.STATUS',  'CRS.STATUS.DATE']
  STUDENT_ACAD_CRED    : ['STC.STATUS',  'STC.STATUS.DATE',  'STC.STATUS.TIME', 'STC.STATUS.REASON']
  STUDENT_PROGRAMS     : ['STPR.STATUS', 'STPR.STATUS.DATE', 'STPR.STATUS.CHGOPR']
  STUDENT_TERMS        : ['STTR.STATUS', 'STTR.STATUS.DATE']
  XCC_ACAD_PROG_REQMTS : ['XCCAPR.STATUS', 'XCCAPR.STATUS.DATE']

pycolleague:
  source: ccdw 
  sourcepath: ./input  # This is default location for File processing

datamart:
  rootfolder: //helix/divisions/IERG/Data/DataMart/A_XNC_Colleague/Downloads/SASDatasets

R:
  scripts_path: //helix/divisions/IERG/R/scripts/
  default: True

config:
  location: self

newlevel:
  newkey: 1